### ISSUE TITLE
[Bug] Grey screen after fullscreen+lock screen

### ISSUE THREAD

**Issue by Flashwalker** [MarmadileManteater/FreeTubeCordova#502]
### Guidelines

- [x] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [x] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [x] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [x] This issue contains only one bug.

### Describe the bug

1. set the player to fullscreen mode and pause the playback, after a while the tablet will lock up and go into sleep state.

2. unlock screen and you will get Freetube as grey screen instead of ui until restarting the app.

### Expected Behavior

paused fullscreen video

### Issue Labels

usability issue

### FreeTube Version

v0.23.2.13

### Operating System Version

Android 14

### Installation Method

.apk

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MarmadileManteater** [comment]
This is a great example of an issue that needs to be documented with a ticket, but your ticket is badly formatted. Please, use the template.

**Comment by MarmadileManteater** [comment]
This issue happens when fullscreen is exited while the app is in the background. I fixed it for videojs, and I thought I fixed it for shaka, but it doesn't seem so.

**Comment by Flashwalker** [comment]
Also fullscreen app go grey after overview via middle button

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hard to record but i do have a screenshot of the Nightly build

Repro steps:
1. Pause fullscreen video
2. Lock screen
3. After x amount of time unlock phone
4. See grey screen

<img width="1280" height="2856" alt="Image" src="https://github.com/user-attachments/assets/e745be93-582b-411f-a1d5-bd8a973bd226" />

**Comment by gweilo8888** [comment]
I see this problem still in the current v0.24.0.2 Beta while watching videos on the AYN Odin 2 Portal running Android 13. My screenshot would look identical to the above except for being on a 1080p landscape-orientation screen, so I'm not attaching one, and my repro steps are identical too, but Ican make screenshots or provide logs if needed.

**Comment by gweilo8888** [comment]
I just made a new discovery which confirms that FreeTube is still active and not entirely locked up when in this state. I powered on my Bluetooth headphones and the program I'd been watching started to play its audio even though I just had the blank, gray screen and no video feed to watch. Hopefully this is helpful in troubleshooting the issue!

**Comment by gweilo8888** [comment]
Just wanted to stop by quickly and confirm this bug remains unfixed in the current release 0.24.1.1
